GAdaNext:
  ModelName : "GAdaNext"
  use_dropout : 0         # Use dropout for training (1/0)
  dropout_prob : 0.1      # Dropout prob for training (0-1)
  channel_size : 32       # Internal channel size for the network
  iou_threshold : 0.25    # Threshold for IOU matching